/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { YDCoursePlatform__factory } from "./YDCoursePlatform__factory";
export { YDToken__factory } from "./YDToken__factory";
